name: manual-train
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "training_runs.id to train"
        required: true
jobs:
  train:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install supabase==2.6.0 ultralytics==8.3.0
      - env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          RUN_ID: ${{ github.event.inputs.run_id }}
        run: python training/pipeline.py --run-id "$RUN_ID"